"""criar tabelas produtos e categorias

Revision ID: 7ab301395e64
Revises: 9581b5d23bf1
Create Date: 2026-03-16 23:40:14.706638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab301395e64'
down_revision: Union[str, Sequence[str], None] = '9581b5d23bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.add_column('produtos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    # FK removida: SQLite não suporta ADD CONSTRAINT via ALTER TABLE
    op.drop_column('produtos', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('produtos', 'categoria_id')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
